GRANT SELECT ON *.* TO 'analytics_read'@'%';
GRANT SELECT, INSERT, UPDATE, CREATE, DROP, RELOAD, SHUTDOWN, PROCESS, INDEX, ALTER, SHOW DATABASES, SUPER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'backupuser'@'%';
GRANT PROXY ON ''@'' TO 'backupuser'@'%';
GRANT SELECT ON *.* TO 'billing_read'@'%';
GRANT USAGE ON *.* TO 'developer'@'%';
GRANT SELECT ON `uniware`.* TO 'developer'@'%';
GRANT SELECT, REPLICATION CLIENT ON *.* TO 'monitoring'@'%';
GRANT REPLICATION SLAVE ON *.* TO 'replication'@'%';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
GRANT PROXY ON ''@'' TO 'root'@'%' WITH GRANT OPTION;
GRANT USAGE ON *.* TO 'uniware'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, EXECUTE ON `uniware`.* TO 'uniware'@'%';
GRANT EXECUTE ON PROCEDURE `uniware`.`tenant_go_live` TO 'uniware'@'%';
GRANT SELECT ON *.* TO 'uniware_read'@'%';
GRANT SELECT, PROCESS ON *.* TO 'developer'@'localhost';
GRANT SELECT ON `uniware`.* TO 'developer'@'localhost';
GRANT SUPER ON *.* TO 'mysql.session'@'localhost';
GRANT SELECT ON `performance_schema`.* TO 'mysql.session'@'localhost';
GRANT SELECT ON `mysql`.`user` TO 'mysql.session'@'localhost';
GRANT USAGE ON *.* TO 'mysql.sys'@'localhost';
GRANT TRIGGER ON `sys`.* TO 'mysql.sys'@'localhost';
GRANT SELECT ON `sys`.`sys_config` TO 'mysql.sys'@'localhost';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
GRANT PROXY ON ''@'' TO 'root'@'localhost' WITH GRANT OPTION;
